apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-ci-role
  namespace: default
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-ci-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: default
roleRef:
  kind: Role
  name: gitlab-ci-role
  apiGroup: rbac.authorization.k8s.io
