version: "2"
services:
  db:
    image: postgres:12
    volumes:
      - ./docker/storage/db:/data
    env_file:
      - .env
  frontend:
    image: node:10.12-stretch
    working_dir: /var/www/frontend
    environment:
      - NODE_ENV=dev
      - HOST=frontend
    volumes:
      - ../frontend:/var/www/frontend:delegated
    ports:
      - "8080:8080"
    command: "npm run serve"
  phpfpm:
    build:
      context: ./infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    links:
      - db:db
      - redis:redis
    volumes:
      - .:/data/www
      - .:/var/www/app
      - ./docker/storage/phpfpm/xdebug:/tmp/xdebug
    env_file:
      - .env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
  nginx:
    image: nginx:stable
    volumes:
      - ./infrastructure/containers/nginx/laravel-dev-frontend:/etc/nginx/conf.d/default.conf
      - ./docker/certificates:/secrets
      - .:/var/www/app
    env_file:
      - .env
    ports:
      - "8000:80"
    links:
      - phpfpm:phpfpm
    environment:
      LARAVEL_ROOT: "/var/www/app"
  artisan_worker:
    build:
      context: ./infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    volumes:
      - .:/var/www/app
    env_file:
      - .env
      
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    links:
      - db:db
      - redis:redis
    entrypoint:
      - php
      - /var/www/app/artisan
    command:
      - "queue:work"
  redis:
    image: redis
    env_file:
      - .env
