apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
data:
  fluent.conf: |-
    <source>
      @type forward
      @id input1
      @label @mainstream
      port {{ .Values.service.internalPort }}      
    </source>
    
    <label @mainstream>
      <match kube.var.log.containers.**_kube-system_**>
        @type null
      </match>
      <match>
        @type file
        path /fluentd/log/myapp
        time_slice_format %Y%m%d%H
      </match>
    </label>

 
