apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-additional-settings
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  additional.php: |
    {{ template "additionalPhp" . }}
