apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-phpini
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  php.ini: |
    {{ template "phpIni" . }}
