apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-env
data:
  app-key: {{ .Values.laravel.app.appKey | b64enc }}
  mail-password: {{ .Values.laravel.mail.password | b64enc }}
{{- if .Values.laravel.mail.sesKey }}
  ses-secret: {{ .Values.laravel.mail.sesSecret | b64enc }}
{{- end }}
{{- if .Values.laravel.storage.azure.enabled }}
  azure-storage-key: {{ .Values.laravel.storage.azure.key | b64enc }}
{{- end }}

{{- if .Values.laravel.storage.minio.enabled }}
  minio-secret: {{ .Values.laravel.storage.minio.secret | b64enc }}
{{- end }}

{{- range $env, $value := .Values.secretEnv }}
  {{ $env }}: {{ $value | b64enc }}
{{- end }}
