{{- if (not .Values.laravel.app.oauthSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
data:
  oauth-public.key: {{ .Values.laravel.app.oauthPublicKey | quote }}
  oauth-private.key: {{ .Values.laravel.app.oauthPrivateKey | quote }}
{{- end -}}
