apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*
        Refresh_Interval 5
        Mem_Buf_Limit 8K
        Buffer_Chunk_Size 3K 

    [FILTER]
        Name   kubernetes
        Match  kube.*

{{ if eq .Values.backend.type "test" }}
    [OUTPUT]
        Name  file
        Match *
        Path /tmp/fluent-bit.log
{{ else if eq .Values.backend.type "forward" }}
    [OUTPUT]
        Name          forward
        Match         *
        Host          {{ if (default false .Values.backend.forward.prefixReleaseToHost) }}{{ .Release.Name }}{{ end }}{{ .Values.backend.forward.host }}
        Port          {{ .Values.backend.forward.port }}
        Time_as_Integer    On
        Retry_Limit False
{{ else if eq .Values.backend.type "es" }}
    [OUTPUT]
        Name  es
        Match *
        Host  {{ .Values.backend.es.host }}
        Port  {{ .Values.backend.es.port }}
        Logstash_Format On
        Retry_Limit False
{{ else if eq .Values.backend.type "influxdb" }}
    [OUTPUT]
        Name  influxdb
        Match *
        Host  {{ if (default false .Values.backend.influxdb.prefixReleaseToHost) }}{{ .Release.Name }}{{ end }}{{ .Values.backend.influxdb.host }}
        Port  {{ .Values.backend.influxdb.port }}
        Database {{ default "fluentbit" .Values.backend.influxdb.database }}
        Sequence_Tag {{ default "_seq" .Values.backend.influxdb.sequenceTag }}
{{- end }}
