kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}-filter-kube
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-filter-kube
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-filter-kube
  namespace: {{ .Release.Namespace }}
