apiVersion: v2
name: Flax & Teal Buckram
description: A Helm chart for Laravel and several related services
name: buckram
version: 0.0.3
keywords:
  - laravel
  - php
home: http://www.flaxandteal.co.uk
sources:
  - http://gitlab.com/flaxandteal/buckram
maintainers:
  - name: Phil Weir
    email: phil.weir@flaxandteal.co.uk
icon: https://gitlab.com/flaxandteal/buckram/raw/master/docs/drawing.svg
engine: gotpl
dependencies:
  - name: redis
    version: 9.1.12
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 6.3.9
    repository: https://charts.bitnami.com/bitnami
  - name: laravel-nginx
    version: 0.0.1
    repository: file://./subcharts/laravel-nginx
  - name: laravel-phpfpm
    version: 0.0.1
    repository: file://./subcharts/laravel-phpfpm
  - name: elastic-stack
    version: 2.0.0
    repository: https://kubernetes-charts.storage.googleapis.com
    tags:
      - elk
